//auth actions
export let LOGINACTION = 'LOGINACTION'
export let ALREADYLOGGEDINFROMSESSIONS = 'ALREADYLOGGEDINFROMSESSIONS'
export let REGISTERUSERACTION = 'REGISTERUSERACTION'

//auth mutations
export let LOGINSUCCESS = 'LOGINSUCCESS'
export let LOGINUNSUCCESS = 'LOGINUNSUCCESS'

//user actions
export let GETUSERSACTION = 'GETUSERSACTION'
export let GETSINGLEUSERACTION = 'GETSINGLEUSERACTION'
export let UPDATEAUSERACTION = 'UPDATEAUSERACTION'
export let EDITUSERACTION = 'EDITUSERACTION'
export let DELETEUSERACTION = 'DELETEUSERACTION'
export let USERTYPEACTION = 'USERTYPEACTION'

//user mutations
export let USERTYPEMUTATION = 'USERTYPEMUTATION'
export let GETUSERSMUTATION = 'GETUSERSMUTATION'
export let GETSINGLEUSERMUTATION = 'GETSINGLEUSERMUTATION'
export let UPDATEAUSERMUTATION = 'UPDATEAUSERMUTATION'
export let EDITUSERMUTATION = 'EDITUSERMUTATION'
export let DELETEUSERMUTATION = 'DELETEUSERMUTATION'

//universal variables

export let GETITEMSACTION = 'GETITEMSACTION'
export let CREATEITEMACTION = 'CREATEITEMACTION'
export let GETSINGLEITEMTOEDITACTION = 'GETSINGLEITEMTOEDITACTION'
export let UPDATEITEMACTION = 'UPDATEITEMACTION'
export let DELETEITEMACTION = 'DELETEITEMACTION'

//universal mutations
export let GETITEMSMUTATION = 'GETITEMSMUTATION'
export let CREATEITEMMUTATION = 'CREATEITEMMUTATION'
export let GETSINGLEITEMTOEDITMUTATION = 'GETSINGLEITEMTOEDITMUTATION'
export let UPDATEITEMMUTATION = 'UPDATEITEMMUTATION'
export let DELETEITEMMUTATION = 'DELETEITEMMUTATION'

//technicion variables
export let ASSIGNTICKET = 'ASSIGNTICKET'
export let ASSIGNTICKETMUTATION = 'ASSIGNTICKETMUTATION'
